films_project/films_app/urls.py
from .import views
from django.urls import path
app_name = 'films_app'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail, name='detail' ),
    path('add/',views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

films_project/films_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('films_app.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

films_project/films_app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')


    def __str__(self):
        return self.name

films_project/films_app/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:

        model = Movie
        fields = ['name','desc', 'year', 'img']

films_project/films_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }

    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'detail.html', {'movie': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
        return redirect('/')
    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)

    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

films_project/templates/add.html
{% extends 'base.html' %}

{% block body %}
<div class="container mt-5">
    <form method="POST" enctype="multipart/form-data" class="custom-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Movie Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter the movie name">
        </div>
        <div class="form-group">
            <label for="desc">Description</label>
            <input type="text" class="form-control" id="desc" name="desc" placeholder="Enter the movie description">
        </div>
        <div class="form-group">
            <label for="year">Release Year</label>
            <input type="text" class="form-control" id="year" name="year" placeholder="Enter the movie release year">
        </div>
        <div class="form-group">
            <label for="img">Image</label>
            <input type="file" class="form-control-file" id="img" name="img">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock %}




<!--<form method="POST" enctype="multipart/form-data">-->
<!--    {% csrf_token %}-->
<!--    <input type="text" name="name" placeholder="Enter the movie name"><br>-->
<!--    <input type="text" name="desc" placeholder="Enter the movie description"><br>-->
<!--    <input type="text" name="year" placeholder="Enter the move release year"><br>-->
<!--    <input type="file" name="img" placeholder="Insert the image"><br>-->
<!--    <input type="submit">-->
<!--</form>-->

films_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark justify-content-between">
  <a class="navbar-brand" style="color: white;">Online MovieStore</a>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search for movies">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

films_project/templates/ch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

films_project/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" >
    {% csrf_token %}
    Do you want to delete this movie?
    <input type="submit" class="btn btn-danger">

{% endblock %}

films_project/templates/detail.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid">
    <div class="row justify-content-center align-items-center full-height">
        <div class="col-md-8">
            <div class="card border-0">
                <div class="row no-gutters">
                    <div class="col-md-5">
                        <img class="card-img" src="{{movie.img.url}}" alt="Movie Image">
                    </div>
                    <div class="col-md-7">
                        <div class="card-body">
                            <h5 class="card-title">{{movie.name}}</h5>
                            <p class="card-text">{{movie.desc}}</p>
                            <div class="btn-group" role="group">
                                <a href="{% url 'films_app:update' movie.id %}" class="btn btn-warning">Update</a>
                                <a href="{% url 'films_app:delete' movie.id %}" class="btn btn-danger">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}



<!--<div class="card" style="width: 20rem;">-->
<!--  <img class="card-img-top" src="{{movie.img.url}}" alt="Card image cap">-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">{{movie.name}}</h5>-->
<!--    <p class="card-text">{{movie.desc}}</p>-->
<!--    <a href="{% url 'films_app:update' movie.id %}" class="btn btn-warning">Update</a>-->
<!--      <a class="btn btn-danger" href="{% url 'films_app:delete' movie.id %}">Delete</a>-->
<!--  </div>-->
<!--</div>-->

<!--<img src="{{movie.img.url}}" width="100" height="100">-->

<!--{{movie.name}}<br>-->
<!--{{movie.desc}}<br>-->
<!--{{movie.year}}-->
<!--<a class="btn btn-warning" href="{% url 'films_app:update' movie.id %}">Update</a>-->
<!--<a class="btn btn-warning" href="{% url 'films_app:delete' movie.id %}">Delete</a>-->

films_project/templates/edit.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data" class="custom-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">Movie Name</label>
                    {{ form.name }}
                </div>
                <div class="form-group">
                    <label for="id_desc">Description</label>
                    {{ form.desc }}
                </div>
                <div class="form-group">
                    <label for="id_year">Release Year</label>
                    {{ form.year }}
                </div>
                <div class="form-group">
                    <label for="id_img">Image</label>
                    {{ form.img }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

<!--<form method="POST" enctype="multipart/form-data">-->
<!--    {% csrf_token %}-->
<!--    {{form.as_p}}-->
<!--    <input type="submit">-->
<!--</form>-->

films_project/templates/index.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <img class="card-img-top" src="{{i.img.url}}" alt="{{i.name}}">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <a href="{% url 'films_app:detail' i.id %}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="container text-center mt-4">
    <a class="btn btn-warning" href="{% url 'films_app:add_movie' %}">Add New Movies</a>
</div>
{% endblock %}


<!--{% for i in movie_list %}-->
<!--<img src="{{i.img.url}}" width="400" height="400">-->
<!--&lt;!&ndash;<a href="{% url 'films_app:detail' i.id %}">{{i.name}}<br></a>&ndash;&gt;-->
<!--<a class="btn btn-primary" href="{% url 'films_app:detail' i.id %}">Details..</a>-->
<!--{% endfor %}-->
<!--<a class="btn btn-warning" href="{% url 'films_app:add_movie' %}">Add</a>-->